"""add_security_analysis_metadata

Revision ID: 5c2468228789
Revises: d8c6adca9a5b
Create Date: 2026-08-22 18:27:24.508796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2468228789'
down_revision: Union[str, None] = 'd8c6adca9a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_records', sa.Column('security_analysis_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_records', 'security_analysis_metadata')
    # ### end Alembic commands ###
