"""Add OTP and Student Type fields

Revision ID: 813bcfe78d29
Revises: 25d7162557f4
Create Date: 2026-08-19 22:35:08.912554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '813bcfe78d29'
down_revision: Union[str, None] = '25d7162557f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('hashed_otp', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('student_profiles', sa.Column('student_type', sa.String(length=50), nullable=True))
    op.add_column('student_profiles', sa.Column('school_board', sa.String(length=100), nullable=True))
    op.add_column('student_profiles', sa.Column('grade', sa.String(length=50), nullable=True))
    op.add_column('student_profiles', sa.Column('school_name', sa.String(length=255), nullable=True))
    op.add_column('student_profiles', sa.Column('university', sa.String(length=255), nullable=True))
    op.add_column('student_profiles', sa.Column('specialization', sa.String(length=255), nullable=True))
    op.add_column('student_profiles', sa.Column('preferred_tutor_languages', sa.JSON(), nullable=True))
    op.drop_column('student_profiles', 'languages')
    op.drop_column('student_profiles', 'institution')
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    op.add_column('student_profiles', sa.Column('institution', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('student_profiles', sa.Column('languages', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('student_profiles', 'preferred_tutor_languages')
    op.drop_column('student_profiles', 'specialization')
    op.drop_column('student_profiles', 'university')
    op.drop_column('student_profiles', 'school_name')
    op.drop_column('student_profiles', 'grade')
    op.drop_column('student_profiles', 'school_board')
    op.drop_column('student_profiles', 'student_type')
    op.drop_table('otp_verifications')
    # ### end Alembic commands ###
