"""Add verification records model

Revision ID: d8c6adca9a5b
Revises: 813bcfe78d29
Create Date: 2026-08-20 21:11:53.775611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8c6adca9a5b'
down_revision: Union[str, None] = '813bcfe78d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tutor_profile_id', sa.String(length=36), nullable=False),
    sa.Column('certificate_id', sa.String(length=36), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('ocr_status', sa.String(length=50), nullable=False),
    sa.Column('certificate_validation_status', sa.String(length=50), nullable=False),
    sa.Column('security_analysis_status', sa.String(length=50), nullable=False),
    sa.Column('university_verification_status', sa.String(length=50), nullable=False),
    sa.Column('face_verification_status', sa.String(length=50), nullable=False),
    sa.Column('liveness_status', sa.String(length=50), nullable=False),
    sa.Column('overall_result', sa.String(length=50), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('manual_review_required', sa.Boolean(), nullable=False),
    sa.Column('ocr_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tutor_profile_id'], ['tutor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tutor_profile_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_records')
    # ### end Alembic commands ###
